baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Melo's Blog"

theme = 'paper'
[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
  name = 'Lucas'
  bio = 'Software Engineer'

  # header social icons
  twitter = 'ApoleraCSGO'               # https://twitter.com/ApoleraCSGO
  github = 'Lucas-Melo0'                 # https://github.com/Lucas-Melo0
  linkedin = 'lucas-melo-bb0999210'             # https://www.linkedin.com/in/lucas-melo-bb0999210/

  [menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10